export enum DeniedCode {
  DO_VALID_ERROR = "DENIED_A02",
  EMAIL_CORRECT_ERROR = "DENIED_A03",
  NICKNAME_CORRECT_ERROR = "DENIED_A04",
  ACCESS_TOKEN_ERROR = "DENIED_A08",
  WORKSPACE_CREATE_ERROR = "DENIED_A10",
  WORKSPACE_NOT_FOUND_ERROR = "DENIED_A11",
}
